spring:
  application:
    name: its-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        refresh-enabled: true



  config:
    import:
      - optional:nacos:its-gateway-service.yaml
server:
  port: 8888
