spring:
  application:
    name: its-generator-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:its-message-service.yml
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/its?currentSchema=its_generator_module,public
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      connect-timeout: 5000
      database: 0
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
server:
  port: 8103

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
  paths-to-match: '/**'
  packages-to-scan: cn.edu.hhu.its.generator.service.controller