spring:
  application:
    name: its-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        heart-beat-interval: 3000
        heart-beat-timeout: 9000
        namespace: public
        ephemeral: true
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:its-user-service.yml
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/its?currentSchema=its_user_module,public
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      connect-timeout: 5000
      database: 0
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
server:
  port: 8101
#文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
  paths-to-match: '/**'
  packages-to-scan: cn.edu.hhu.its.user.service.controller

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

