spring:
  application:
    name: its-resource-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  datasource:
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/its?currentSchema=its_generator_module,public
    driver-class-name: org.postgresql.Driver
server:
  port: 8102

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
  paths-to-match: '/**'
  packages-to-scan: cn.edu.hhu.its.generator.service.controller